feat: add check for latest version
Xmader/musescore-downloader pull request #106
Opened 2021-01-15 08:11 UTC by RubenVerg

if you're running msdl via `npm i -g musescore-downloader` instead of `npx`, checks if the latest version is installed.

couldn't really test it obviously but seems to be logically working

2021-01-17 23:40 UTC, Xmader requested changes

2021-01-17 23:40 UTC, Xmader commented on src/npm-data.ts
> +  return (/musescore-downloader@([\d\.]+)/).exec((await exec('npm list -g musescore-downloader')).stdout)![1].trim()
too complicated

```suggestion
  return require('../package.json').version
```

2021-01-17 23:40 UTC, Xmader commented on src/cli.ts
> +    console.log(chalk.yellowBright(`Your installed version (${await installedVersion()}) of the musescore-downloader CLI is not the latest one (${await latestVersion()})!\nRun npm i -g musescore-down
```suggestion
  if (!(await isNpx())) {
    const installed = await installedVersion()
    const latest = await latestVersion()
    if (!isLatest(installed, latest)) {
      console.log(chalk.yellowBright(`Your installed version (${installed}) of the musescore-downloader CLI is not the latest one (${latest})!\nRun npm i -g musescore-downloader to update.`))
    }
```

2021-01-18 07:03 UTC, RubenVerg commented
reading the package.json makes more sense, yeah

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Xmader <notifications@github.com>
Sent: Monday, January 18, 2021 12:41:01 AM
To: Xmader/musescore-downloader <musescore-downloader@noreply.github.com>
Cc: Ruben Vergani <RubenVerg@outlook.com>; Author <author@noreply.github.com>
Subject: Re: [Xmader/musescore-downloader] feat: add check for latest version (#106)


@Xmader requested changes on this pull request.

________________________________

In src/npm-data.ts<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXmader%2Fmusescore-downloader%2Fpull%2F106%23discussion_r559255940&data=04%7C01%7C%7Cf263518f6b824edd0ef608d8bb4159bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637465236633798668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hcjDeZqG2UhPrQu%2BQiIBBV0thoekFF%2BRWBsy98URISg%3D&reserved=0>:

> @@ -0,0 +1,21 @@

+import { exec as _exec } from 'child_process'

+import { promisify } from 'util'

+

+const exec = promisify(_exec)

+

+export async function isNpx() {

+  const output = await exec('npm list -g musescore-downloader')

+  return output.stdout.includes('(empty)')

+}

+

+export async function installedVersion() {

+  return (/musescore-downloader@([\d\.]+)/).exec((await exec('npm list -g musescore-downloader')).stdout)![1].trim()



too complicated

⬇️ Suggested change

-  return (/musescore-downloader@([\d\.]+)/).exec((await exec('npm list -g musescore-downloader')).stdout)![1].trim()

+  return require('../package.json').version



________________________________

In src/cli.ts<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXmader%2Fmusescore-downloader%2Fpull%2F106%23discussion_r559256831&data=04%7C01%7C%7Cf263518f6b824edd0ef608d8bb4159bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637465236633808672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3CnxBvSoRc8SifdV2UPTfzsgsO3HyW8hJC%2BVnDH%2FI2I%3D&reserved=0>:

> +  if (!(await isNpx()) && !(await isLatest())) {

+    console.log(chalk.yellowBright(`Your installed version (${await installedVersion()}) of the musescore-downloader CLI is not the latest one (${await latestVersion()})!\nRun npm i -g musescore-downloader to update.`))



⬇️ Suggested change

-  if (!(await isNpx()) && !(await isLatest())) {

-    console.log(chalk.yellowBright(`Your installed version (${await installedVersion()}) of the musescore-downloader CLI is not the latest one (${await latestVersion()})!\nRun npm i -g musescore-downloader to update.`))

+  if (!(await isNpx())) {

+    const installed = await installedVersion()

+    const latest = await latestVersion()

+    if (!isLatest(installed, latest)) {

+      console.log(chalk.yellowBright(`Your installed version (${installed}) of the musescore-downloader CLI is not the latest one (${latest})!\nRun npm i -g musescore-downloader to update.`))

+    }



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXmader%2Fmusescore-downloader%2Fpull%2F106%23pullrequestreview-570107058&data=04%7C01%7C%7Cf263518f6b824edd0ef608d8bb4159bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637465236633808672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B4H6c5UxZpOu87YQnrY89Ni9fXLcm7Ee2G%2Fg%2FMAU3Gg%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMRJI3CFIVJR2LLA6UOAPZ3S2NYQ3ANCNFSM4WDV6ECA&data=04%7C01%7C%7Cf263518f6b824edd0ef608d8bb4159bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637465236633818662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BZW%2FH6FjaqPwzM9uKerZE6U1uILOfbAi6HFvpa4uS8M%3D&reserved=0>.

2021-01-20 15:45 UTC, merged